<?php
/**
 * Pmclain_Twilio extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GPL v3 License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://www.gnu.org/licenses/gpl.txt
 *
 * @category       Pmclain
 * @package        Twilio
 * @copyright      Copyright (c) 2017
 * @license        https://www.gnu.org/licenses/gpl.txt GPL v3 License
 */

/** @var \Pmclain\Twilio\Block\Adminhtml\Usage\Index $block */
?>

<p><em>**</em>Some disclaimer about how the report something, something, blah, blah is not an offical Twilio bill.</p>

<?php $today = $block->getUsageToday(); ?>
<h3>Today</h3>
<p>Count: <?php echo $today['count']; ?></p>
<p>Price: <?php echo $today['price']; ?></p>
<br />
<?php $mtd = $block->getMtdUsage(); ?>
<h3>Month to Date</h3>
<p>Count: <?php echo $mtd['count']; ?></p>
<p>Price: <?php echo $mtd['price']; ?></p>
<br />
<?php $lastMonth = $block->getLastMonthUseage(); ?>
<h3>Last Month</h3>
<p>Count: <?php echo $lastMonth['count']; ?></p>
<p>Price: <?php echo $lastMonth['price']; ?></p>